todo/urls.py
from django.urls import path
from . import views


app_name='todo'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('create/',views.CreateView.as_view(),name='create'),
    path('detail/<int:pk>',views.DetailView.as_view(),name='detail'),
    path('delete/<int:pk>',views.DeleteView.as_view(),name='delete'),
    path('update/<int:pk>',views.UpdateView.as_view(),name='update'),
]

todoproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls')),
]

todo/models.py
from django.db import models

PRIORITY=(('danger','high'),('info','normal'),('success','low'))

class Post(models.Model):
    title=models.CharField('タイトル',max_length=30)
    text=models.TextField('本文')
    priority=models.CharField(
        '優先度',
        max_length=50,
        choices=PRIORITY,
        null=True
    )
    duedate=models.DateField('期限',null=True)
    
    def __str__(self):
        return self.title
    

todo/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        
        model=Post
        fields=['title','text','priority','duedate']
        
class PostUpdateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','text','priority','duedate']

todo/views.py
from django.urls import reverse_lazy
from .models import Post
from django.views import generic
from .forms import PostCreateForm,PostUpdateForm

class IndexView(generic.ListView):
    model=Post
    
class CreateView(generic.CreateView): 
    model=Post
    form_class=PostCreateForm
    success_url=reverse_lazy('todo:index')
    
    def __str__(self):
        return self.title
    
class DetailView(generic.DetailView):
    model=Post
    
    
class DeleteView(generic.DeleteView):
    model=Post
    success_url=reverse_lazy('todo:index')
    
class UpdateView(generic.UpdateView):
    model=Post
    form_class=PostUpdateForm
    success_url=reverse_lazy('todo:index')
    
    
    

todo/templates/todo/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>todolist</title>
  </head>
  <body>

    {% block header %}
    {% endblock %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

todo/templates/todo/post_confirm_delete.html
{% extends 'todo/base.html' %}



{% block content %} 
<form action="" method="POST">

<button type="submit">削除する</button>
{%csrf_token%}
</form>

{% endblock %}

todo/templates/todo/post_detail.html
{% extends 'todo/base.html' %}



{% block content %} 
<div class="card">
    <div class="card-header bg-dark text-white">
        <p>{{post.title}}　　|　　{{post.duedate}}</p>
    </div>
    <div class="card-body">
        <p>{{post.text}}</p>
    </div>
  </div>

{% endblock %}

todo/templates/todo/post_form.html
{% extends 'todo/base.html' %}

{% block content %}
<form action="" method="POST">
    {% for field in form %}
    <div class="form-group">
      <label for="formGroupExampleInput">{{field.label_tag}}</label>
      <p>{{field}}</p>
    </div>
    {%endfor%}
    {% csrf_token %}
<button type="submit" class="btn btn-primary">送信</button>
</form>

{% endblock %}

todo/templates/todo/post_list.html
{% extends 'todo/base.html' %}


{% block header %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">TodoList</h1>
    <p class="lead">TodoListを使って毎日を効率的に過ごしましょう。</p>
  </div>
</div>

{% endblock %}


{% block content %} 
<a href="{% url 'todo:create'%}">新規登録</a>
{% for post in post_list %}
<div class="alert alert-{{post.priority}}" role="alert">
  <p>{{post.title}}</p>
    <a class='btn btn-primary' href="{% url 'todo:delete' post.pk%}">削除</a>
    <a class="btn btn-info" href="{% url 'todo:update' post.pk%}">編集</a>
    <a class="btn btn-success" href="{% url 'todo:detail' post.pk%}">詳細</a>
</div>


{%endfor%}
{% endblock %}

todo/templates/todo/post_update.html
{% extends 'todo/base.html' %}



{% block content %} 
<form action="" method="POST">
  {% for field in form %}
  <div class="form-group">
    <label for="formGroupExampleInput">{{field.label_tag}}</label>
    <p>{{field}}</p>
  </div>
  {%endfor%}
  {% csrf_token %}
<button type="submit" class="btn btn-primary">更新する</button>
</form>
{% endblock %}